myData = read.csv("party.csv")
mean1 = mean(subset(myData, particpate == 0)$mile1)
mean2 = mean(subset(myData, particpate == 0)$mile2)
mean3 = mean(subset(myData, particpate == 0)$mile3)
mean4 = mean(subset(myData, particpate == 0)$mile4)
mean5 = mean(subset(myData, particpate == 1)$mile1)
mean6 = mean(subset(myData, particpate == 1)$mile2)
mean7 = mean(subset(myData, particpate == 1)$mile3)
mean8 = mean(subset(myData, particpate == 1)$mile4)
sd1 = sd(subset(myData, particpate == 0)$mile1)
sd2 = sd(subset(myData, particpate == 0)$mile2)
sd3 = sd(subset(myData, particpate == 0)$mile3)
sd4 = sd(subset(myData, particpate == 0)$mile4)
sd5 = sd(subset(myData, particpate == 1)$mile1)
sd6 = sd(subset(myData, particpate == 1)$mile2)
sd7 = sd(subset(myData, particpate == 1)$mile3)
sd8 = sd(subset(myData, particpate == 1)$mile4)
party0 = c(mean1,mean2,mean3,mean4)
party1 = c(mean5,mean6,mean7,mean8)
party0T = c(mean1+2*sd1,mean2+2*sd2,mean3+2*sd3,mean4+2*sd4)
party0B = c(mean1-2*sd1,mean2-2*sd2,mean3-2*sd3,mean4-2*sd4)
party1T = c(mean5+2*sd5,mean6+2*sd6,mean7+2*sd7,mean8+2*sd8)
party1B = c(mean5-2*sd5,mean6-2*sd6,mean7-2*sd7,mean8-2*sd8)
plot(party0, type = 'l', ylim = c(-1000,1000), col = 'red')
lines(party0T, col = 'red')
lines(party0B, col = 'red')
lines(party1, col = 'blue')
lines(party1T, col = 'blue')
lines(party1B, col = 'blue')
plot(party0, type = 'l', ylim = c(20,40), col = 'red')
lines(party1, col = 'blue')
partyMean = rbind(party0,party1)
partyMean
partySD = c(sd1,sd2,sd3,sd4,sd5,sd6,sd7,sd8)
partySD
plot(myData)